# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLvqQ978p-xM5Hfz8D3eNRZm0VZfF1cN
"""

import sys
!{sys.executable} -m pip install streamlit

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import streamlit as st
import joblib
import numpy as np

# Load models
# Assuming 'r_model.pkl' and 'cl_model.pkl' are pre-saved model files.
# If you intend to save new models, please define 'stack' and 'models["SVM"]' first.
model1 = joblib.load("r_model.pkl") # Loads the regression model
model2 = joblib.load("cl_model.pkl") # Loads the classification model

st.title("ML Model Deployment Demo")

# Collect input values
x1 = st.number_input("age")
x2 = st.number_input("sex")
x3 = st.number_input("bmi")
x4 = st.number_input("children")
x5 = st.number_input("smoker")
x6 = st.number_input("region")

# Predict button
if st.button("Predict"):
    inputs = np.array([[x1, x2, x3, x4, x5, x6]])
    # Assuming model1 is the intended model for prediction. Change to model2 if needed.
    pred = model1.predict(inputs)[0]
    st.success(f"Prediction: {pred}")